--INSERT into PRODUCT ( ID_PRODUCT, NAME, PRICE, WEIGHT) VALUES (1, 'Television', 149.99, 10.5)
--INSERT into PRODUCT ( ID_PRODUCT, NAME, PRICE, WEIGHT) VALUES (2, 'Radio', 100, 3.5)
--INSERT into PRODUCT ( ID_PRODUCT, NAME, PRICE, WEIGHT) VALUES (3, 'Routeur', 76.99, 2)
--INSERT into PRODUCT ( ID_PRODUCT, NAME, PRICE, WEIGHT) VALUES (4, 'Serveur Cloud', 2999.99, 100)
--INSERT into PRODUCT ( ID_PRODUCT, NAME, PRICE, WEIGHT) VALUES (5, 'Appareil photo reflex', 495, 1.2)
--INSERT into PRODUCT ( ID_PRODUCT, NAME, PRICE, WEIGHT) VALUES (6, 'Iphone', 799.99, 0.8)
--
--INSERT into ORD ( ID_ORD, STATUS, SHIPMENTAMOUNT, TOTALAMOUNT, WEIGHT) VALUES (1, 'PAID', 25, 274.99, 14)
--INSERT into ORD ( ID_ORD, STATUS, SHIPMENTAMOUNT, TOTALAMOUNT, WEIGHT) VALUES (2, 'PENDING', 0, 1294.99, 2)
--
--INSERT into BILL ( ID_BILL, AMOUNT, DATE_CREATION) VALUES (1, 274.99, '2020-05-21')
--
--INSERT into ORD_LIST_PRODUCT  ( ORD_ID_ORD, LIST_PRODUCT_ID_PRODUCT) VALUES (1, 1)
--INSERT into ORD_LIST_PRODUCT  ( ORD_ID_ORD, LIST_PRODUCT_ID_PRODUCT) VALUES (1, 2)
--INSERT into ORD_LIST_PRODUCT  ( ORD_ID_ORD, LIST_PRODUCT_ID_PRODUCT) VALUES (2, 5)
--INSERT into ORD_LIST_PRODUCT  ( ORD_ID_ORD, LIST_PRODUCT_ID_PRODUCT) VALUES (2, 6)



